{% set name = "scherbelberg" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scherbelberg-{{ version }}.tar.gz
  sha256: 4eadae83d7f269683c6bbc6fdda964136b8582a16cecaa5be1ad1b51f155ac60

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - scherbelberg = scherbelberg._cli:cli

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - click
    - dask
    - hcloud
    - pyyaml
    - tabulate
    - typeguard

test:
  imports:
    - scherbelberg
    - scherbelberg._cli
  commands:
    - pip check
    - scherbelberg --help
  requires:
    - pip

about:
  home: https://github.com/pleiszenburg/scherbelberg
  summary: HPC cluster deployment and management for the Hetzner Cloud
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://scherbelberg.readthedocs.io/
  dev_url: https://github.com/pleiszenburg/scherbelberg

extra:
  recipe-maintainers:
    - s-m-e
